export const CREATE_BRIEF_CONSTANTS = {
  HEADER_MAX_LENGTH: 200,
  CONTENT_MAX_LENGTH: 10000,
  FOOTER_MAX_LENGTH: 200,
  CHARACTER_COUNTER_WARNING_THRESHOLD: 0.8, // 80%
  CHARACTER_COUNTER_DANGER_THRESHOLD: 0.95, // 95%
} as const;
